flags: {}
packages:
- '.'
- location:
    git: git@github.com:Twinside/HPDF
    commit: 090c08ab61a237c721a307f5cf9fd33f3988b82e
  extra-dep: true
extra-deps:
- boxes-0.1.4
- conduit-audio-0.2
resolver: lts-3.0
