flags: {}
packages:
- '.'
- location:
    git: git@github.com:Twinside/HPDF
    commit: 090c08ab61a237c721a307f5cf9fd33f3988b82e
extra-deps:
- boxes-0.1.4
- conduit-audio-0.1
resolver: nightly-2015-06-28
